# Generated by Django 3.2.3 on 2021-05-29 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediate_table_of_cometaries_and_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_comments', to='webapp.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк комента',
                'verbose_name_plural': 'Лайки коментариев',
            },
        ),
    ]
